version: '2'
services:
  wordpress-dev:
    restart: always
    build:
      context: .
      args:
        HTTP_AUTH_ENABLED: ${HTTP_AUTH_ENABLED}
        HTTP_AUTH_USER: ${HTTP_AUTH_USER}
        HTTP_AUTH_PASSWORD: ${HTTP_AUTH_PASSWORD}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        WORDPRESS_SHA1: ${WORDPRESS_SHA1}
        WPCLI_VERSION: ${WPCLI_VERSION}
        WPCLI_SHA1: ${WPCLI_SHA1}
        PHPUNIT_VERSION: ${PHPUNIT_VERSION}
        PHPUNIT_SHA1: ${PHPUNIT_SHA1}
        XDEBUG_PORT: ${XDEBUG_PORT}
    container_name: wordpress-dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb-dev
    links:
      - mariadb-dev
  mariadb-dev:
    restart: always
    image: mariadb
    container_name: mariadb-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin-dev:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    depends_on:
      - mariadb-dev
    links:
      - mariadb-dev
    ports:
      - 8090:80
    environment:
      PMA_HOST: ${PMA_HOST}
